server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka
      # 不注册自己
    register-with-eureka: true
    # 不拉取服务
    fetch-registry: true
# 连接池
spring:
  application:
    name: cloud-bill-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bill-manager?serverTimezone=GMT%2B8&useSSL=false
  thymeleaf:
    cache: false #关闭thymeleaf缓存
  main:
    allow-circular-references: true
# 整合mybatis
mybatis:
  type-aliases-package: com.nxg.entity #别名扫描
  mapper-locations: classpath:/mybatis/*.xml

